### ISSUE TITLE
The download link for pre-trained transformer is inaccessible. 

### ISSUE THREAD

**Issue by HXX5656** [cusuh/CoGS#2]
Your research is a valuable contribution to our field of study. I hope this message finds you well. I came across your repository and noticed that the download link for the pre-trained transformer weight file (https://www.dropbox.com/s/abuozyjbtk64mxv/last.ckpt?dl=0) is not accessible. I would be very grateful if you could grant me permission to download this file. My email address is 767043131@qq.com.
Thank you for your time and consideration!

**Comment by cusuh** [comment]
Thank you for bringing this to my attention! I've modified the permissions for the link provided so you should be able to download the weights now.
